# nginx proxy address - http://172.17.0.1:3000

name: grafana
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: grafana/grafana:latest
    container_name: grafana-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      GF_SERVER_ROOT_URL: https://${BASE_HOST_NAME:-$HOSTNAME}
      GF_SECURITY_ADMIN_USER: ${APP_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${APP_ADMIN_PASS:-changeme_admin_password}
      GF_SECURITY_SECRET_KEY: ${APP_SECRET_KEY:-changeme_secret_key}
      GF_INSTALL_PLUGINS: ""
      GF_SMTP_ENABLED: "true"
      GF_SMTP_HOST: ${EMAIL_SERVER_HOST:-172.17.0.1}:${EMAIL_SERVER_PORT:-587}
      GF_SMTP_USER: ${EMAIL_SERVER_LOGIN_NAME:-}
      GF_SMTP_PASSWORD: ${EMAIL_SERVER_LOGIN_PASS:-}
      GF_SMTP_FROM_ADDRESS: ${EMAIL_SERVER_MAIL_FROM:-grafana@${BASE_DOMAIN_NAME:-${BASE_HOST_NAME}}}
    ports:
      - '172.17.0.1:3000:3000'
    volumes:
      - './volumes/data/grafana:/var/lib/grafana'
    user: '${SERVICE_USER:-1000}:${SERVICE_GROUP:-1000}'
    networks:
      - grafana

networks:
  grafana:
    name: grafana
    external: false
